---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kova-namespace-user
  namespace: kova

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kova-namespace-user-full-access
  namespace: kova
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling", "cache.example.com", "coordination.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kova-namespace-user-view
  namespace: kova
subjects:
- kind: ServiceAccount
  name: kova-namespace-user
  namespace: kova
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kova-namespace-user-full-access
